services: 
  sqlserver_db:
    image: devolutions/dvls-sql-linux:latest
    tty: true
    expose:
      - 1433
      - 1434
    networks:
      internal:
        ipv4_address: 172.30.0.44
    environment:
      MSSQL_USER: ${DB_USER}
      MSSQL_PASSWORD: ${DB_PASSWORD}
      WHITELISTED_ORIGINS: ${WHITELISTED_ORIGINS}
    volumes:
      - ./data-sql:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:42424"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  dvls_server:
    image: devolutions/dvls-server-linux:latest
    depends_on:
      sqlserver_db:
        condition: service_healthy
    networks:
      internal:
        ipv4_address: 172.30.0.45
    ports:
      - 5544:443
    environment: 
        MSSQL_USER: ${DB_USER}
        MSSQL_PASSWORD: ${DB_PASSWORD}
        DVLS_USER: ${DVLS_USER}
        DVLS_PASSWORD: ${DVLS_PASSWORD}
        CERT_PASSWORD: ${CERT_PASSWORD}
    volumes:
      - ./data-dvls:/app/persistent
      
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
